"""Add profile_image_url to user table

Revision ID: 9580053f4420
Revises: e1c2a3b4d5f6
Create Date: 2026-04-17 15:30:28.707775
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '9580053f4420'
down_revision = 'e1c2a3b4d5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image_url')
    # ### end Alembic commands ###
